// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatBuffersModels
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Address : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Address GetRootAsAddress(ByteBuffer _bb) { return GetRootAsAddress(_bb, new Address()); }
  public static Address GetRootAsAddress(ByteBuffer _bb, Address obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Address __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int AddressId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Street { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetStreetBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetStreetBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetStreetArray() { return __p.__vector_as_array<byte>(6); }
  public int Number { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<FlatBuffersModels.Address> CreateAddress(FlatBufferBuilder builder,
      int address_id = 0,
      StringOffset streetOffset = default(StringOffset),
      int number = 0) {
    builder.StartTable(3);
    Address.AddNumber(builder, number);
    Address.AddStreet(builder, streetOffset);
    Address.AddAddressId(builder, address_id);
    return Address.EndAddress(builder);
  }

  public static void StartAddress(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddAddressId(FlatBufferBuilder builder, int addressId) { builder.AddInt(0, addressId, 0); }
  public static void AddStreet(FlatBufferBuilder builder, StringOffset streetOffset) { builder.AddOffset(1, streetOffset.Value, 0); }
  public static void AddNumber(FlatBufferBuilder builder, int number) { builder.AddInt(2, number, 0); }
  public static Offset<FlatBuffersModels.Address> EndAddress(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatBuffersModels.Address>(o);
  }
}


static public class AddressVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*AddressId*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*Street*/, false)
      && verifier.VerifyField(tablePos, 8 /*Number*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
