// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatBuffersModels
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Employee : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Employee GetRootAsEmployee(ByteBuffer _bb) { return GetRootAsEmployee(_bb, new Employee()); }
  public static Employee GetRootAsEmployee(ByteBuffer _bb, Employee obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Employee __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int EmployeeId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(6); }
  public string Email { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetEmailBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetEmailBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetEmailArray() { return __p.__vector_as_array<byte>(8); }

  public static Offset<FlatBuffersModels.Employee> CreateEmployee(FlatBufferBuilder builder,
      int employee_id = 0,
      StringOffset nameOffset = default(StringOffset),
      StringOffset emailOffset = default(StringOffset)) {
    builder.StartTable(3);
    Employee.AddEmail(builder, emailOffset);
    Employee.AddName(builder, nameOffset);
    Employee.AddEmployeeId(builder, employee_id);
    return Employee.EndEmployee(builder);
  }

  public static void StartEmployee(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddEmployeeId(FlatBufferBuilder builder, int employeeId) { builder.AddInt(0, employeeId, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static void AddEmail(FlatBufferBuilder builder, StringOffset emailOffset) { builder.AddOffset(2, emailOffset.Value, 0); }
  public static Offset<FlatBuffersModels.Employee> EndEmployee(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatBuffersModels.Employee>(o);
  }
}


static public class EmployeeVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*EmployeeId*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*Name*/, false)
      && verifier.VerifyString(tablePos, 8 /*Email*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
